export const christmasTrees = [
    {
        price: 300,
        colorCode: "yellow",
        includeFoot: "Yes",
        payment: "mobilePay",
        date: "17/12/2023",
        time: "10:00",
    },
    {
        price: 400,
        colorCode: "blue",
        includeFoot: "No",
        payment: "cash",
        date: "18/12/2023",
        time: "11:30",
    },
    {
        price: 550,
        colorCode: "red",
        includeFoot: "Yes",
        payment: "mobilePay",
        date: "19/12/2023",
        time: "12:45",
    },
    {
        price: 250,
        colorCode: "white",
        includeFoot: "Yes",
        payment: "cash",
        date: "20/12/2023",
        time: "14:15",
    },
    {
        price: 600,
        colorCode: "pink",
        includeFoot: "No",
        payment: "mobilePay",
        date: "21/12/2023",
        time: "15:30",
    },
    {
        price: 350,
        colorCode: "yellow",
        includeFoot: "Yes",
        payment: "cash",
        date: "22/12/2023",
        time: "16:45",
    },
    {
        price: 450,
        colorCode: "blue",
        includeFoot: "No",
        payment: "mobilePay",
        date: "23/12/2023",
        time: "17:30",
    },
    {
        price: 500,
        colorCode: "red",
        includeFoot: "Yes",
        payment: "cash",
        date: "24/12/2023",
        time: "18:00",
    },
    {
        price: 300,
        colorCode: "yellow",
        includeFoot: "Yes",
        payment: "mobilePay",
        date: "17/12/2023",
        time: "10:00",
    },
    {
        price: 400,
        colorCode: "blue",
        includeFoot: "No",
        payment: "cash",
        date: "18/12/2023",
        time: "11:30",
    },
    {
        price: 550,
        colorCode: "red",
        includeFoot: "Yes",
        payment: "mobilePay",
        date: "19/12/2023",
        time: "12:45",
    },
    {
        price: 250,
        colorCode: "white",
        includeFoot: "Yes",
        payment: "cash",
        date: "20/12/2023",
        time: "14:15",
    },
    {
        price: 600,
        colorCode: "pink",
        includeFoot: "No",
        payment: "mobilePay",
        date: "21/12/2023",
        time: "15:30",
    },
    {
        price: 350,
        colorCode: "yellow",
        includeFoot: "Yes",
        payment: "cash",
        date: "22/12/2023",
        time: "16:45",
    },
    {
        price: 450,
        colorCode: "blue",
        includeFoot: "No",
        payment: "mobilePay",
        date: "23/12/2023",
        time: "17:30",
    },
    {
        price: 500,
        colorCode: "red",
        includeFoot: "Yes",
        payment: "cash",
        date: "24/12/2023",
        time: "18:00",
    },
    {
        price: 550,
        colorCode: "white",
        includeFoot: "No",
        payment: "cash",
        date: "25/12/2023",
        time: "10:30",
    },
    {
        price: 400,
        colorCode: "yellow",
        includeFoot: "Yes",
        payment: "mobilePay",
        date: "26/12/2023",
        time: "12:00",
    },
    {
        price: 350,
        colorCode: "blue",
        includeFoot: "Yes",
        payment: "cash",
        date: "27/12/2023",
        time: "14:45",
    },
    {
        price: 500,
        colorCode: "red",
        includeFoot: "No",
        payment: "mobilePay",
        date: "28/12/2023",
        time: "15:15",
    },
    {
        price: 300,
        colorCode: "white",
        includeFoot: "Yes",
        payment: "cash",
        date: "29/12/2023",
        time: "16:30",
    },
    {
        price: 600,
        colorCode: "pink",
        includeFoot: "No",
        payment: "mobilePay",
        date: "30/12/2023",
        time: "17:45",
    },
    {
        price: 450,
        colorCode: "yellow",
        includeFoot: "No",
        payment: "cash",
        date: "31/12/2023",
        time: "18:00",
    },
];
